name = "pdf-to-text"
compatibility_date = "2024-11-11"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "olistic-pdf-edi"

[observability.logs]
enabled = true


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"



# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
